version: '3.8'
services:
    postgres:
        build: ./postgres
        shm_size: 512mb
        environment:
            POSTGRES_PASSWORD: postgresisawesome
            #DATABASE_PASSWORD:
        volumes:
            - postgres12:/var/lib/postgresql/data
        restart: on-failure:3
    mauro-data-mapper:
        build:
            context: mauro-data-mapper
            args:
                MDM_APPLICATION_COMMIT: 4.5.0
                MDM_UI_COMMIT: 6.1.0
                ADDITIONAL_PLUGINS: ""
                MDM_UI_THEME_NAME: "default"
        environment:
            #DATABASE_PASSWORD:
            MDM_FQ_HOSTNAME: localhost
            MDM_PORT: 8082
            MDM_AUTHORITY_URL: "http://localhost:8082"
            MDM_AUTHORITY_NAME: "mdm-docker"
            EMAIL_USERNAME: ""
            EMAIL_PASSWORD: ""
            EMAIL_HOST: "smtp.gmail.com"
        ports:
            - "8082:8080"
        depends_on:
            - postgres
        volumes:
            - lucene_index:/lucene
            - ./shared_volumes/logs/maurodatamapper:/usr/local/tomcat/logs
            - ./shared_volumes/tmp:/tmp
        restart: on-failure:3
# Persistence capability to systems,
# Any volumes labelled below will ensure persistence when containers removed unless the volume is removed as well
volumes:
    postgres12:
        driver: local
    lucene_index:
        driver: local
