version: '3'
services:
    postgres:
        build: ./postgres
        environment:
            POSTGRES_PASSWORD: postgresisawesome
        volumes:
            - postgres12:/var/lib/postgresql/data
        restart: on-failure:3
    mauro-data-mapper:
        build:
            context: mauro-data-mapper
            args:
                MDM_BASE_VERSION: develop
                MDM_APPLICATION_COMMIT: develop
                MDM_UI_COMMIT: develop
                TOMCAT_VERSION: 9.0.27-jdk12-adoptopenjdk-openj9
        environment:
            PGPASSWORD: postgresisawesome
            MDM_FQ_HOSTNAME: localhost
            MDM_PORT: 8082
        ports:
            - "8082:8080"
        depends_on:
            - postgres
        volumes:
            - lucene_index:/lucene
            - ./shared_volumes/logs/maurodatamapper:/usr/local/tomcat/logs
            - ./shared_volumes/tmp:/tmp
        restart: on-failure:3
# Persistence capability to systems,
# Any volumes labelled below will ensure persistence when containers removed unless the volume is removed as well
volumes:
    postgres12:
        driver: local
    lucene_index:
        driver: local
